environment:
  matrix:
    - nodejs_version: "Current"
    - nodejs_version: "LTS"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm
  - npm i
test_script:
  - node -v
  - npm -v
  - npm test
build: off
