environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm
  - npm i
test_script:
  - node -v
  - npm -v
  - npm test
build: off
